INSERT INTO AJUSTES..BIT_EJECUCIONES(PROCESO, DESCRIPCION, ESTADO)
VALUES('LIMPIEZA', 'INICIO', 1)
 
INSERT INTO AJUSTES..BIT_EJECUCIONES(PROCESO, DESCRIPCION, ESTADO)
VALUES('LIMPIEZA', 'FIN', 1)
 
INSERT INTO AJUSTES..BIT_EJECUCIONES(PROCESO, DESCRIPCION, ESTADO)
VALUES('LIMPIEZA', 'FIN', 0)
-----------------------------INSERCIONES CARGA ARCHIVOS
INSERT INTO AJUSTES..BIT_EJECUCIONES(PROCESO,SUB_PROCESO, DESCRIPCION, ESTADO)
VALUES('LIMPIEZA','CARGA_ARCHIVOS', 'INICIO', 1)
 
INSERT INTO AJUSTES..BIT_EJECUCIONES(PROCESO,SUB_PROCESO, DESCRIPCION, ESTADO)
VALUES('LIMPIEZA','CARGA_ARCHIVOS', 'FIN', 1)
 
INSERT INTO AJUSTES..BIT_EJECUCIONES(PROCESO,SUB_PROCESO, DESCRIPCION, ESTADO)
VALUES('LIMPIEZA','CARGA_ARCHIVOS', 'FIN', 0)
-----------------------------INSERCIONES TRANSFORMACION
INSERT INTO AJUSTES..BIT_EJECUCIONES(PROCESO,SUB_PROCESO, DESCRIPCION, ESTADO)
VALUES('LIMPIEZA','TRANSFORMACION', 'INICIO', 1)
 
INSERT INTO AJUSTES..BIT_EJECUCIONES(PROCESO,SUB_PROCESO, DESCRIPCION, ESTADO)
VALUES('LIMPIEZA','TRANSFORMACION', 'FIN', 1)
 
INSERT INTO AJUSTES..BIT_EJECUCIONES(PROCESO,SUB_PROCESO, DESCRIPCION, ESTADO)
VALUES('LIMPIEZA','TRANSFORMACION', 'FIN', 0)
----------------------------INSERCIONES MIGRACION
INSERT INTO AJUSTES..BIT_EJECUCIONES(PROCESO,SUB_PROCESO, DESCRIPCION, ESTADO)
VALUES('LIMPIEZA','MIGRACION', 'INICIO', 1)
 
INSERT INTO AJUSTES..BIT_EJECUCIONES(PROCESO,SUB_PROCESO, DESCRIPCION, ESTADO)
VALUES('LIMPIEZA','MIGRACION', 'FIN', 1)
 
INSERT INTO AJUSTES..BIT_EJECUCIONES(PROCESO,SUB_PROCESO, DESCRIPCION, ESTADO)
VALUES('LIMPIEZA','MIGRACION', 'FIN', 0)