USE [MINI_SUPER]
GO

/****** Object:  Table [dbo].[DETALLE]    Script Date: 4/08/2024 23:19:23 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[DETALLE](
	[IDPedido] [int] NULL,
	[IDProducto] [int] NULL,
	[Cantidad] [int] NULL
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[DETALLE]  WITH CHECK ADD  CONSTRAINT [FK_DETALLE_PEDIDO] FOREIGN KEY([IDPedido])
REFERENCES [dbo].[PEDIDO] ([IDPedido])
GO

ALTER TABLE [dbo].[DETALLE] CHECK CONSTRAINT [FK_DETALLE_PEDIDO]
GO

ALTER TABLE [dbo].[DETALLE]  WITH CHECK ADD  CONSTRAINT [FK_DETALLE_PRODUCTO] FOREIGN KEY([IDProducto])
REFERENCES [dbo].[PRODUCTO] ([IDProducto])
GO

ALTER TABLE [dbo].[DETALLE] CHECK CONSTRAINT [FK_DETALLE_PRODUCTO]
GO


