/*
CREATE DATABASE AJUSTES
CREATE DATABASE SERVIDOR_A
CREATE DATABASE SERVIDOR_B
CREATE DATABASE SERVIDOR_C
*/

SELECT * FROM STANGING_LIMPIEZA
 
SELECT * 
INTO #TRANSFROMACION
FROM STANGING_LIMPIEZA
 
--COMPROBAR FILAS VACIAS
 
SELECT *
FROM #TRANSFROMACION
 
--LLENAR FILAS VACIAS
--Nombre_Completo
UPDATE T
SET T.Nombre_Completo = NULL
FROM #TRANSFROMACION T
WHERE Nombre_Completo = ''
 
--Marca
UPDATE T
SET T.Marca = NULL
FROM #TRANSFROMACION T
WHERE Marca = ''
 
--Plaza
UPDATE T
SET T.Plaza = NULL
FROM #TRANSFROMACION T
WHERE Plaza = ''
 
--Tarjeta_Pago
UPDATE T
SET T.Tarjeta_Pago = NULL
FROM #TRANSFROMACION T
WHERE Tarjeta_Pago = ''
 
--Fecha_Pago
UPDATE T
SET T.Fecha_Pago = NULL
FROM #TRANSFROMACION T
WHERE Fecha_Pago = ''
 
---------COMPROBAR RESTO DE DATOS
SELECT *
FROM #TRANSFROMACION
 
--MEJORAR LOS NOMBRES COMPLETOS
SELECT REPLACE(Nombre_Completo, '_', ' ') Nombre_Completo, Marca, Plaza, Tarjeta_Pago, Fecha_Pago, Descuento, Precio
INTO #TRANS_1
FROM #TRANSFROMACION
 
---------COMPROBAR RESTO DE DATOS
SELECT *
FROM #TRANS_1