---!!EJECUTAR COMO 10 VECES¡¡
UPDATE PARTICIPANTE
SET CARNET_PARTICIPANTE = CAST(YEAR(FECHA_REGISTRO) AS VARCHAR(4)) + '-' + CAST(CHECKSUM(NEWID()) % 999999 + 1 AS VARCHAR(6))
--DESPUES ESTO
WHERE CARNET_PARTICIPANTE = '2024-*'
 
---REVISION SI AUN EXISTEN
SELECT CARNET_PARTICIPANTE
FROM PARTICIPANTE
WHERE CARNET_PARTICIPANTE = '2024-*'

--JALAMOS LOS CARNETS
UPDATE INSCRIPCION
SET INSCRIPCION.CARNET_PARTICIPANTE = PARTICIPANTE.CARNET_PARTICIPANTE
FROM INSCRIPCION
JOIN PARTICIPANTE ON INSCRIPCION.COD_INSCRIPCION = PARTICIPANTE.CODIGO_PARTICIPANTE

