DECLARE @FECHA DATE
SET @FECHA = '2024/05/16';

WITH GASTO_PASAJERO AS (
    SELECT 
        B.COD_PASAJERO,
        SUM(C.PRECIO) AS PrecioTotal
    FROM BOLETO B
    INNER JOIN VUELO V ON B.COD_VUELO = V.COD_VUELO
    INNER JOIN CLASE C ON B.COD_CLASE = C.COD_CLASE
    GROUP BY B.COD_PASAJERO, MONTH(V.FECHA_SALIDA)
)

SELECT 
    C.NOMBRE AS 'NOMBRE',
    C.TELEFONO AS 'TELEFONO',
    C.DIRECCION AS 'DIRECCION',
    DATEDIFF(YEAR, C.FECHA_NACIMIENTO, @FECHA) AS 'EDAD',
    C.FECHA_NACIMIENTO AS 'FECHA_NACIMIENTO',
    C.NIT AS 'NIT',
    P.PASAPORTE AS 'NO_PASAPORTE',
    P.ASIST_ESPECIAL AS 'ASISTENCIA ESPECIAL',
    B.N_BOLETO AS 'NO_BOLETO',
    B.N_ASIENTO AS 'NO_ASIENTO',
    CASE
        WHEN B.COD_CLASE = 1 THEN 'BUSSINES'
        WHEN B.COD_CLASE = 2 THEN 'PRIMERA CLASSE'
        WHEN B.COD_CLASE = 3 THEN 'TURISTA'
    END AS CLASE,
    G.PrecioTotal AS 'GASTADO'
FROM CLIENTE C
JOIN PASAJERO P ON C.COD_CLIENTE = P.COD_CLIENTE
JOIN BOLETO B ON B.COD_PASAJERO = P.COD_PASAJERO
JOIN VUELO V ON V.COD_VUELO = B.COD_VUELO
LEFT JOIN GASTO_PASAJERO G ON G.COD_PASAJERO = P.COD_PASAJERO
